<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPINPUNW0595" ignored="0" name="Test1" tests="2" failures="1" timestamp="23 Oct 2022 11:02:46 GMT" time="64.875" errors="0">
  <testcase name="Task_01_lambdatestAssignment" time="9.294" classname="TestCases.LambdaTestSeleniumAdvancedTestScripts">
    <failure type="java.lang.AssertionError" message="expected [TestingWhiz Integration | LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest]">
      <![CDATA[java.lang.AssertionError: expected [TestingWhiz Integration | LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest]
	at TestCases.LambdaTestSeleniumAdvancedTestScripts.Task_01_lambdatestAssignment(LambdaTestSeleniumAdvancedTestScripts.java:93)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Task_01_lambdatestAssignment -->
  <testcase name="Task_02_lambdatestAssignment" time="13.128" classname="TestCases.LambdaTestSeleniumAdvancedTestScripts"/>
</testsuite> <!-- Test1 -->
