<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="EPINPUNW0595" name="TestCases.LambdaTestSeleniumAdvancedTestScripts" tests="4" failures="2" timestamp="23 Oct 2022 11:02:50 GMT" time="132.839" errors="0">
  <testcase name="Task_01_lambdatestAssignment" time="33.965" classname="TestCases.LambdaTestSeleniumAdvancedTestScripts">
    <failure type="java.lang.AssertionError" message="expected [TestingWhiz Integration | LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest]">
      <![CDATA[java.lang.AssertionError: expected [TestingWhiz Integration | LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at TestCases.LambdaTestSeleniumAdvancedTestScripts.Task_01_lambdatestAssignment(LambdaTestSeleniumAdvancedTestScripts.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- Task_01_lambdatestAssignment -->
  <testcase name="Task_02_lambdatestAssignment" time="34.041" classname="TestCases.LambdaTestSeleniumAdvancedTestScripts"/>
  <testcase name="Task_01_lambdatestAssignment" time="27.728" classname="TestCases.LambdaTestSeleniumAdvancedTestScripts">
    <failure type="java.lang.AssertionError" message="expected [TestingWhiz Integration | LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest]">
      <![CDATA[java.lang.AssertionError: expected [TestingWhiz Integration | LambdaTest] but found [Running Automation Tests Using TestingWhiz LambdaTest | LambdaTest]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at TestCases.LambdaTestSeleniumAdvancedTestScripts.Task_01_lambdatestAssignment(LambdaTestSeleniumAdvancedTestScripts.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- Task_01_lambdatestAssignment -->
  <testcase name="Task_02_lambdatestAssignment" time="37.105" classname="TestCases.LambdaTestSeleniumAdvancedTestScripts"/>
</testsuite> <!-- TestCases.LambdaTestSeleniumAdvancedTestScripts -->
